# Generated by Django 5.1.3 on 2024-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('sender_id', models.IntegerField(db_index=True)),
                ('notification_type', models.CharField(choices=[('FOLLOW_REQUEST', 'Follow Request'), ('FOLLOW_ACCEPT', 'Follow Request Accepted'), ('POST_LIKE', 'Post Like'), ('POST_COMMENT', 'Post Comment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('post_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('sender_username', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', 'created_at'], name='notificatio_recipie_18c9bd_idx'), models.Index(fields=['recipient_id', 'is_read'], name='notificatio_recipie_dd6756_idx')],
            },
        ),
    ]
