# Generated by Django 5.1.1 on 2024-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_like_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
