# Generated by Django 5.1.1 on 2024-11-05 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_contentuser_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
