# Generated by Django 5.1.1 on 2024-10-19 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
