apiVersion: v1
kind: Secret
metadata:
  name: connection-service-secret
stringData:
  SECRET_KEY: "django-insecure-quc1n20^5b*o7rkimf*x8!5!21c(#w$k8)d1uzj4+s(3y_x3)4"
  DB_NAME: "connection_db"
  DB_USER: "postgres"
  DB_PASSWORD: "Sadique785"
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-service-configmap
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "connection-service,connection-service.default.svc.cluster.local,localhost,127.0.0.1,musify.sadique.live"
  CORS_ALLOWED_ORIGINS: "http://gateway-service:8000,http://gateway-service.default.svc.cluster.local:8000,https://musify.sadique.live"
  CSRF_TRUSTED_ORIGINS: "http://gateway-service:8000,http://gateway-service.default.svc.cluster.local:8000,https://musify.sadique.live"
  DB_HOST: "auth-service.c3iy20uqsyh9.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5433"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "connection-consumer-group"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations-connection
spec:
  template:
    metadata:
      name: django-migrations-connection-pod
      labels:
        app: django-migrations-connection
    spec:
      containers:
      - name: connection-service
        image: vssadique123/musify_connection:test10
        command: ['python', 'manage.py', 'migrate']
        envFrom:
        - configMapRef:
            name: connection-service-configmap
        - secretRef:
            name: connection-service-secret
      restartPolicy: Never
  backoffLimit: 5

---

apiVersion: v1
kind: Service
metadata:
  name: connection-service
spec:
  selector:
    app: connection-service
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-service
  labels:
    app: connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: connection-service
    spec:
      containers:
        - name: connection-service
          image: vssadique123/musify_connection:test10
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: connection-service-configmap
            - secretRef:
                name: connection-service-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        - name: kafka-consumer-connection
          image: vssadique123/musify_connection:test10
          command: ["python", "manage.py", "start_kafka_consumer"]
          envFrom:
            - configMapRef:
                name: connection-service-configmap
            - secretRef:
                name: connection-service-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"