# Generated by Django 5.1 on 2024-09-16 15:04

from django.db import migrations, models
import django.db.models.deletion

def remove_and_readd_user_field(apps, schema_editor):
    Profile = apps.get_model('authentication', 'Profile')
    
    # Remove the existing OneToOneField
    schema_editor.delete_model(Profile)
    
    # Add the OneToOneField back with the updated configuration
    schema_editor.create_model(Profile)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20240916_1903'),
    ]

    operations = [
        migrations.RunPython(remove_and_readd_user_field),
    ]