# Generated by Django 5.1 on 2024-09-18 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20240916_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='name',
            field=models.CharField(default='your name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False)
            ),
    ]
