# Generated by Django 5.1 on 2024-09-18 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userrole_name_alter_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='city', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='your name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False)
            ),
        
    ]
