# Generated by Django 5.1 on 2024-09-19 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_genre_talent_alter_role_id_profile_talents'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='profiles_with_genre', to='authentication.genre'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
